### ISSUE TITLE
Pre-Defined Applications

### ISSUE THREAD

**Issue by MrTumnis** [winapps-org/winapps#255] opened 2024-09-13 20:06 UTC
When I try to add predefined applications to ~/winapps/apps, I am unable to see them in the list during the installation process. The solutions was to add them to ~/.local/bin/winapps-src/apps/.

**Comment by oskardotglobal** [comment] 2024-09-14 08:00
This is a duplicate of #249.

**Closed by oskardotglobal** 2024-09-14 08:00 UTC
