### ISSUE TITLE
Add netcat as a depencency and check if it is installed

### ISSUE THREAD

**Issue by wutscher** [winapps-org/winapps#154] opened 2024-07-22 12:58 UTC
I just tried setting up winapps and encountered the error:
> Failed to establish a connection with Windows at '127.0.0.1:3389'.

After quite some time troubleshooting I checked the install script and found that it expects the `nc` command to exist (line 825) and causes this error if it isn't installed.

A hint in the README and a check to see if it's installed would go a long way to prevent others from chasing ghosts in the future

**Comment by KernelGhost** [comment] 2024-07-22 20:59
Hello @wutscher, thank you for your interest in the project! I apologise for the issue caused by the recent installation script rewrite. To address this, I have added additional dependency checks for both 'netcat' and 'arp' in PR #153. This issue should be resolved once the PR is merged. Please let me know if you have any further questions or concerns.

**Closed** 2024-07-23 07:35 UTC
