### ISSUE TITLE
Setup.sh: Network Configuration Error (13) even though xfreerdp successfully connects

### ISSUE THREAD

**Issue by tristanRW** [winapps-org/winapps#260] opened 2024-09-19 05:00 UTC
Hi,
I have followed the setupinstructions for libvirt and also setup static IP address to be "192.168.122.11". When I run setup.sh it prints this [setup.log](https://github.com/user-attachments/files/17053705/setup.log)

I tried connecting directly to the vm using xfreerdp3 and there is a certificate I have to accept by pressing Y and I can connect without problems afterwards.

The log in ~/.local/share/winapps/winapps.log does not get created so I am at somewhat of a loss at what to do.

**Comment by oskardotglobal** [comment] 2024-09-19 05:25
Please enable debugging in your WinApps config, then the winapps.log will be created

**Comment by tristanRW** [comment] 2024-09-19 05:29
> Please enable debugging in your WinApps config, then the winapps.log will be created

I tried, but no matter what I set in the config the file does not get created.

**Comment by oskardotglobal** [comment] 2024-09-19 06:00
You have to create the config yourself..

**Comment by oskardotglobal** [comment] 2024-09-19 06:01
Did you enable RDP inside the VM?

**Comment by tristanRW** [comment] 2024-09-19 06:08
Yes.

I did some more testing and found that while `xfreerdp3 /v:192.168.122.11:3389` successfully connects to my VM after prompting for username & password (since it is not given), `timeout 5 nc -z 192.168.122.11 3389 &>/dev/null` fails.

**Comment by tristanRW** [comment] 2024-09-19 06:14
If I change `waCheckPortOpen()` like this:
`function waCheckPortOpen() {
    # Print feedback.
    echo -n "Checking for an open RDP Port on Windows... "

    # Declare variables.
    local VM_MAC="" # Stores the MAC address of the Windows VM.

    # Obtain Windows VM IP Address (FOR 'libvirt' ONLY)
    # Note: 'RDP_IP' should not be empty if 'WAFLAVOR' is 'docker', since it is set to localhost before this function is called.
    if [ -z "$RDP_IP" ] && [ "$WAFLAVOR" = "libvirt" ]; then
        VM_MAC=$(virsh domiflist "$VM_NAME" | grep -oE "([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})") # VM MAC address.
        RDP_IP=$(ip neigh show | grep "$VM_MAC" | grep -oE "([0-9]{1,3}\.){3}[0-9]{1,3}")         # VM IP address.

        if [ -z "$RDP_IP" ]; then
            # Complete the previous line.
            echo -e "${FAIL_TEXT}Failed!${CLEAR_TEXT}\n"

            # Display the error type.
            echo -e "${ERROR_TEXT}ERROR:${CLEAR_TEXT} ${BOLD_TEXT}NETWORK CONFIGURATION ERROR.${CLEAR_TEXT}"

            # Display the error details.
            echo -e "${INFO_TEXT}The IP address of the Windows VM '${VM_NAME}' could not be found.${CLEAR_TEXT}"

            # Display the suggested action(s).
            echo "--------------------------------------------------------------------------------"
            echo "Please ensure networking is properly configured for the Windows VM."
            echo "--------------------------------------------------------------------------------"

            # Terminate the script.
            return "$EC_NO_IP"
        fi
    fi

    # Check for an open RDP port.
    #if ! timeout 5 nc -z "$RDP_IP" "$RDP_PORT" &>/dev/null; then
    #    # Complete the previous line.
    #    echo -e "${FAIL_TEXT}Failed!${CLEAR_TEXT}\n"

    #    # Display the error type.
    #    echo -e "${ERROR_TEXT}ERROR:${CLEAR_TEXT} ${BOLD_TEXT}NETWORK CONFIGURATION ERROR.${CLEAR_TEXT}"

    #    # Display the error details.
    #    echo -e "${INFO_TEXT}Failed to establish a connection with Windows at '${RDP_IP}:${RDP_PORT}'.${CLEAR_TEXT}"

    #    # Display the suggested action(s).
    #    echo "--------------------------------------------------------------------------------"
    #    echo "Please ensure Remote Desktop is configured on Windows as per the WinApps README."
    #    echo "--------------------------------------------------------------------------------"

    #    # Terminate the script.
    #    return "$EC_BAD_PORT"
    #fi

    # Print feedback.
    echo -e "${DONE_TEXT}Done!${CLEAR_TEXT}"
}`
then setup.sh works as expected.

**Comment by oskardotglobal** [comment] 2024-09-19 06:30
Do you have netcat installed?

**Comment by tristanRW** [comment] 2024-09-19 06:33
`Name            : gnu-netcat
Version         : 0.7.1-10
Description     : GNU rewrite of netcat, the network piping application
Architecture    : x86_64
URL             : http://netcat.sourceforge.net/
Licenses        : GPL-2.0-only
Groups          : None
Provides        : netcat
Depends On      : glibc
Optional Deps   : None
Required By     : None
Optional For    : eos-bash-shared
Conflicts With  : None
Replaces        : netcat
Installed Size  : 66,42 KiB
Packager        : kpcyrd <kpcyrd@archlinux.org>
Build Date      : Mi 15 Mai 2024 21:34:39 HKT
Install Date    : Mi 18 Sep 2024 13:17:35 HKT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature`

**Comment by oskardotglobal** [comment] 2024-09-19 10:51
Can you try loading the RDPWindows.reg from the latest commit again?

**Comment by tristanRW** [comment] 2024-09-19 10:53
It's definitely an issue with the netcat command. I sucessfully used the setup when it was commented out. Reimporting the registry keys in windows yields the same results. 🤔

**Comment by tristanRW** [comment] 2024-09-19 10:57
Though after installation I face the issue that the main script (./bin/winapps) does not connect to the default qemu session (qemu:///system) that is setup during the installation according to the guide. I had to apply the fix in #198. Which is, weirdly enough, closed despite not being fixed to date.

**Comment by itiligent** [comment] 2024-09-20 04:26
If you installed Windows as per the readme in the last 24 hrs,  it might be worth checking the RDPApps.reg file as this would produce behaviour similar (you can access over RDP but cant launch apps over RDP.  The reg file was broken for perhaps a week or so as per issue #261 and only fixed 17hrs ago.

**Comment by friday06** [comment] 2024-09-21 07:36
i've been trying to install, getting the same error

**Comment by tristanRW** [comment] 2024-09-21 12:37
> If I change `waCheckPortOpen()` like this:
> 
> ```
> function waCheckPortOpen() {
>     # Print feedback.
>     echo -n "Checking for an open RDP Port on Windows... "
> 
>     # Declare variables.
>     local VM_MAC="" # Stores the MAC address of the Windows VM.
> 
>     # Obtain Windows VM IP Address (FOR 'libvirt' ONLY)
>     # Note: 'RDP_IP' should not be empty if 'WAFLAVOR' is 'docker', since it is set to localhost before this function is called.
>     if [ -z "$RDP_IP" ] && [ "$WAFLAVOR" = "libvirt" ]; then
>         VM_MAC=$(virsh domiflist "$VM_NAME" | grep -oE "([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})") # VM MAC address.
>         RDP_IP=$(ip neigh show | grep "$VM_MAC" | grep -oE "([0-9]{1,3}\.){3}[0-9]{1,3}")         # VM IP address.
> 
>         if [ -z "$RDP_IP" ]; then
>             # Complete the previous line.
>             echo -e "${FAIL_TEXT}Failed!${CLEAR_TEXT}\n"
> 
>             # Display the error type.
>             echo -e "${ERROR_TEXT}ERROR:${CLEAR_TEXT} ${BOLD_TEXT}NETWORK CONFIGURATION ERROR.${CLEAR_TEXT}"
> 
>             # Display the error details.
>             echo -e "${INFO_TEXT}The IP address of the Windows VM '${VM_NAME}' could not be found.${CLEAR_TEXT}"
> 
>             # Display the suggested action(s).
>             echo "--------------------------------------------------------------------------------"
>             echo "Please ensure networking is properly configured for the Windows VM."
>             echo "--------------------------------------------------------------------------------"
> 
>             # Terminate the script.
>             return "$EC_NO_IP"
>         fi
>     fi
> 
>     # Check for an open RDP port.
>     #if ! timeout 5 nc -z "$RDP_IP" "$RDP_PORT" &>/dev/null; then
>     #    # Complete the previous line.
>     #    echo -e "${FAIL_TEXT}Failed!${CLEAR_TEXT}\n"
> 
>     #    # Display the error type.
>     #    echo -e "${ERROR_TEXT}ERROR:${CLEAR_TEXT} ${BOLD_TEXT}NETWORK CONFIGURATION ERROR.${CLEAR_TEXT}"
> 
>     #    # Display the error details.
>     #    echo -e "${INFO_TEXT}Failed to establish a connection with Windows at '${RDP_IP}:${RDP_PORT}'.${CLEAR_TEXT}"
> 
>     #    # Display the suggested action(s).
>     #    echo "--------------------------------------------------------------------------------"
>     #    echo "Please ensure Remote Desktop is configured on Windows as per the WinApps README."
>     #    echo "--------------------------------------------------------------------------------"
> 
>     #    # Terminate the script.
>     #    return "$EC_BAD_PORT"
>     #fi
> 
>     # Print feedback.
>     echo -e "${DONE_TEXT}Done!${CLEAR_TEXT}"
> }
> ```
> 
> then setup.sh works as expected.

Commenting out as shown in the setup.sh fixed it for me. Since rdp connected, the netcat check was redundant. Should be similar for you if you have the same issue. 👍🏻

**Comment by friday06** [comment] 2024-09-22 11:53
well, that worked out for me too, now i'm having some certificate issues. https://paste.mozilla.org/UKp15rK4

**Comment by tristanRW** [comment] 2024-09-22 12:04
If you find the time, please file an issue for the certificate issues and write how you fixed it. 👍🏻

**Comment by friday06** [comment] 2024-09-22 12:35
> If you find the time, please file an issue for the certificate issues and write how you fixed it. 👍🏻

it's showing error 14 now lol!

**Comment by friday06** [comment] 2024-09-22 17:23
> If you find the time, please file an issue for the certificate issues and write how you fixed it. 👍🏻

i found this on stackexchange, dk if it'll be helpful or not | https://unix.stackexchange.com/questions/732917/linux-rdp-client-connect-to-machine-with-self-signed-certificate

**Comment by tristanRW** [comment] 2024-09-23 14:39
I noticed that `timeout 5 nc -z "$RDP_IP" "$RDP_PORT" &>/dev/null;` also leads to a failed app start sometimes (Exits with $BAD_PORT) and made another issue regarding this, see #270 .
The solution will probably fix both.

**Comment by AkechiShiro** [comment] 2024-11-01 23:07
To understand the solution here is we remove the netcat check, is that correct ? @tristanRW

**Comment by tristanRW** [comment] 2024-11-02 02:24
So the thing is that at least for me, removing the netcat command fixes the appstartup problem and makes the start of apps more responsive, since it removes a 5 second timeout.

My solution would be, to remove the port-check, since the log is verbose enough for debugging purposes, if someone encounteres issues.

**Comment by AkechiShiro** [comment] 2024-11-02 13:52
If you'd be willing to open a PR for this change @tristanRW please do so mentioning the fix for this issue, if not, please let us know and we'll try and open a PR at some point

**Comment by Qianxilihulu** [comment] 2024-11-11 04:40
Same problem here, described in #323.

**Comment by oskardotglobal** [comment] 2024-12-07 17:16
Closing this in favour of #270 as the issue is described in further detail there.

**Closed by oskardotglobal** 2024-12-07 17:16 UTC
Labels: bug
